# Generated by Django 4.2 on 2026-01-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
