# Generated by Django 4.2 on 2025-12-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_reported_by_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postattachment',
            name='image',
            field=models.FileField(upload_to='post_attachments'),
        ),
    ]
