# Generated by Django 4.2 on 2025-12-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_postattachment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
