# Generated by Django 4.2 on 2026-01-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0011_postattachment_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postattachment",
            name="image",
        ),
        migrations.AddField(
            model_name="postattachment",
            name="url",
            field=models.URLField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
